"""Public-facing routes: contact, reach, admission, ground0, diagnostic, etc."""
import asyncio
import httpx
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, EmailStr

from core import (
    db, logger,
    MAILERLITE_API_TOKEN, MAILERLITE_URL,
    COACH_EMAIL, FRONTEND_URL,
    send_mailersend_email,
)

router = APIRouter()


# ── Models ────────────────────────────────────────────────────────────────────
class ContactForm(BaseModel):
    name: str
    email: EmailStr
    phone: Optional[str] = None
    mc: Optional[str] = None
    authorityAge: Optional[str] = None
    inquiryType: Optional[str] = None
    message: Optional[str] = None


class PartnerInquiryForm(BaseModel):
    name: str
    email: EmailStr
    company: str
    role: str
    message: Optional[str] = None


class DiagnosticSubmit(BaseModel):
    email: EmailStr
    score: int
    result: str
    red_count: int
    yellow_count: int


class REACHCategoryScores(BaseModel):
    r: int
    e: int
    a: int
    c: int
    h: int


class REACHSubmit(BaseModel):
    email: EmailStr
    result: str
    total_score: int
    category_scores: REACHCategoryScores
    open_response: Optional[str] = None


class AdmissionSubmit(BaseModel):
    name: str
    email: EmailStr
    usdot_number: str
    cohort_preference: str
    message: Optional[str] = None


class AdmissionRequestNew(BaseModel):
    carrier_name: str
    email: EmailStr
    dot_mc_number: Optional[str] = None
    authority_activation_date: Optional[str] = None
    compliance_status: str
    lane: str
    message: Optional[str] = None


class Ground0Submit(BaseModel):
    email: EmailStr


class SinsChecklistCapture(BaseModel):
    email: EmailStr


class CPMEmailCapture(BaseModel):
    email: EmailStr


# ── Helpers ───────────────────────────────────────────────────────────────────
def _build_reach_email(result: str, total_score: int, scores: REACHCategoryScores, email: str) -> tuple:
    CATEGORY_NAMES = {"r": "Resources", "e": "Experience", "a": "Authority Setup", "c": "Commitment", "h": "Hustle & Capacity"}
    MAX_PER = 6
    MAX_TOTAL = 30
    score_dict = {"r": scores.r, "e": scores.e, "a": scores.a, "c": scores.c, "h": scores.h}
    flagged = [CATEGORY_NAMES[k] for k, v in score_dict.items() if v < MAX_PER * 0.6]
    score_pct = round((total_score / MAX_TOTAL) * 100)

    def score_bar(score: int, max_score: int = MAX_PER) -> str:
        filled = round((score / max_score) * 10)
        bar = "█" * filled + "░" * (10 - filled)
        return f'<span style="font-family:monospace;color:#C5A059;letter-spacing:1px;">{bar}</span>'

    def category_rows() -> str:
        rows = ""
        for k, label in CATEGORY_NAMES.items():
            s = score_dict[k]
            color = "#C5A059" if s >= MAX_PER * 0.6 else "#E8590F"
            rows += f'<tr><td style="padding:8px 0;font-size:13px;color:rgba(255,255,255,0.75);width:140px;">{label}</td><td style="padding:8px 0;">{score_bar(s)}</td><td style="padding:8px 0 8px 12px;font-size:13px;color:{color};font-weight:600;">{s}/{MAX_PER}</td></tr>'
        return rows

    header_base = f'<div style="font-family:\'Inter\',sans-serif;max-width:600px;margin:0 auto;background:#002244;color:#f4f7fb;padding:48px 40px;"><p style="font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:#C5A059;margin:0 0 28px;border-top:4px solid #C5A059;padding-top:20px;">LaunchPath Operating Standard &nbsp;|&nbsp; REACH Assessment Result</p>'
    score_block = f'<div style="background:#0F1E35;border-radius:6px;padding:20px 24px;margin:0 0 28px;"><p style="font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:rgba(197,160,89,0.75);margin:0 0 16px;">YOUR SCORES</p><table style="width:100%;border-collapse:collapse;">{category_rows()}</table><div style="border-top:1px solid rgba(255,255,255,0.08);margin-top:12px;padding-top:12px;"><span style="font-size:12px;color:rgba(255,255,255,0.50);">Total: </span><span style="font-size:14px;font-weight:700;color:#C5A059;">{total_score}/{MAX_TOTAL} &nbsp;({score_pct}%)</span></div></div>'
    footer = '<p style="font-size:12px;color:rgba(255,255,255,0.28);margin:36px 0 0;line-height:1.6;">This result was generated by the LaunchPath REACH Assessment.<br>LaunchPath Operating Standard &nbsp;·&nbsp; Accuracy Over Hype. Systems Over Shortcuts.</p></div>'

    if result == "GO":
        subject = "REACH Result: GO — You're cleared to move forward."
        html = header_base + f'<p style="font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:#4CAF50;margin:0 0 6px;">RESULT</p><h1 style="font-family:\'Manrope\',sans-serif;font-size:32px;font-weight:700;color:#ffffff;margin:0 0 6px;">GO</h1><p style="font-size:16px;color:rgba(255,255,255,0.65);margin:0 0 28px;">Your readiness profile clears you to begin the implementation sequence.</p><p style="font-size:15px;color:rgba(255,255,255,0.78);line-height:1.85;margin:0 0 24px;">Your REACH score indicates you have the foundational resources, authority setup, and operational commitment needed to install the LaunchPath Operating Standard in the next 90 days.</p>{score_block}<p style="font-size:14px;color:rgba(255,255,255,0.65);line-height:1.75;margin:0 0 28px;">Your next step is the Operator Portal. Your Implementation Sequence — 10 compliance tasks assigned by week — is already loaded and waiting.</p><a href="{FRONTEND_URL}/portal" style="display:inline-block;background:#C5A059;color:#002244;font-weight:700;font-size:14px;letter-spacing:0.06em;text-transform:uppercase;padding:16px 32px;text-decoration:none;border-radius:4px;">Enter the Operator Portal →</a>{footer}'
    elif result == "WAIT":
        gap_list = "".join(f'<li style="margin-bottom:6px;">{g}</li>' for g in flagged) if flagged else "<li>Review all five domains before proceeding.</li>"
        subject = "REACH Result: WAIT — Address these gaps before proceeding."
        html = header_base + f'<p style="font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:#F59E0B;margin:0 0 6px;">RESULT</p><h1 style="font-family:\'Manrope\',sans-serif;font-size:32px;font-weight:700;color:#ffffff;margin:0 0 6px;">WAIT</h1><p style="font-size:16px;color:rgba(255,255,255,0.65);margin:0 0 28px;">Your profile shows gaps that should be addressed before you begin the full implementation sequence.</p><p style="font-size:15px;color:rgba(255,255,255,0.78);line-height:1.85;margin:0 0 24px;">A WAIT result does not mean you\'re not ready to operate — it means your current position in one or more domains creates elevated risk if you proceed without a structured plan.</p>{score_block}<div style="background:#1A1000;border-left:3px solid #F59E0B;padding:20px 24px;margin:0 0 28px;"><p style="font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:#F59E0B;margin:0 0 12px;">Domains flagged for attention</p><ul style="font-size:14px;color:rgba(255,255,255,0.75);line-height:1.75;margin:0;padding-left:18px;">{gap_list}</ul></div><a href="{FRONTEND_URL}/ground-0-briefing" style="display:inline-block;background:#C5A059;color:#002244;font-weight:700;font-size:14px;letter-spacing:0.06em;text-transform:uppercase;padding:16px 32px;text-decoration:none;border-radius:4px;margin-right:12px;">Begin Ground 0 →</a><a href="{FRONTEND_URL}/reach-diagnostic" style="display:inline-block;background:transparent;color:#C5A059;font-weight:700;font-size:14px;letter-spacing:0.06em;text-transform:uppercase;padding:15px 24px;text-decoration:none;border-radius:4px;border:1px solid rgba(197,160,89,0.45);">Retake Assessment →</a>{footer}'
    else:
        gap_list = "".join(f'<li style="margin-bottom:6px;">{g}</li>' for g in flagged) if flagged else "<li>Review all five compliance domains immediately.</li>"
        subject = "REACH Result: NO-GO — Your current position requires intervention."
        html = header_base + f'<p style="font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:#E8590F;margin:0 0 6px;">RESULT</p><h1 style="font-family:\'Manrope\',sans-serif;font-size:32px;font-weight:700;color:#ffffff;margin:0 0 6px;">NO-GO</h1><p style="font-size:16px;color:rgba(255,255,255,0.65);margin:0 0 28px;">Your current position carries significant compliance risk. Immediate structured action is required.</p><p style="font-size:15px;color:rgba(255,255,255,0.78);line-height:1.85;margin:0 0 24px;">A NO-GO result means your profile reflects multiple unresolved gaps across critical compliance domains.</p>{score_block}<div style="background:#1A0500;border-left:3px solid #E8590F;padding:20px 24px;margin:0 0 28px;"><p style="font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:#E8590F;margin:0 0 12px;">Critical gaps identified</p><ul style="font-size:14px;color:rgba(255,255,255,0.75);line-height:1.75;margin:0;padding-left:18px;">{gap_list}</ul></div><a href="{FRONTEND_URL}/ground-0-briefing" style="display:inline-block;background:#C5A059;color:#002244;font-weight:700;font-size:14px;letter-spacing:0.06em;text-transform:uppercase;padding:16px 32px;text-decoration:none;border-radius:4px;margin-right:12px;">Begin Ground 0 →</a><a href="{FRONTEND_URL}/contact" style="display:inline-block;background:transparent;color:#C5A059;font-weight:700;font-size:14px;letter-spacing:0.06em;text-transform:uppercase;padding:15px 24px;text-decoration:none;border-radius:4px;border:1px solid rgba(197,160,89,0.45);">Contact LaunchPath →</a>{footer}'
    return subject, html


# ── Routes ────────────────────────────────────────────────────────────────────
@router.get("/")
async def root():
    return {"message": "Hello World"}


@router.post("/contact")
async def submit_contact(form: ContactForm):
    parts = form.name.strip().split(" ", 1)
    first = parts[0]
    last = parts[1] if len(parts) > 1 else ""
    payload = {
        "email": form.email, "status": "active",
        "fields": {"name": first, "last_name": last, "phone": form.phone or "", "company": form.mc or "", "lead_source": "contact_form"},
    }
    if form.authorityAge:
        payload["fields"]["authority_age"] = form.authorityAge
    if form.inquiryType:
        payload["fields"]["inquiry_type"] = form.inquiryType
    if form.message:
        payload["fields"]["contact_message"] = form.message[:1000]
    headers = {"Authorization": f"Bearer {MAILERLITE_API_TOKEN}", "Content-Type": "application/json", "Accept": "application/json"}
    async with httpx.AsyncClient(timeout=10) as http:
        resp = await http.post(MAILERLITE_URL, json=payload, headers=headers)
    if resp.status_code not in (200, 201):
        logger.error(f"MailerLite error {resp.status_code}: {resp.text}")
        raise HTTPException(status_code=502, detail="Could not save contact. Please try again.")
    return {"ok": True}


@router.post("/partners")
async def submit_partner_inquiry(form: PartnerInquiryForm):
    parts = form.name.strip().split(" ", 1)
    first = parts[0]
    last = parts[1] if len(parts) > 1 else ""
    payload = {
        "email": form.email, "status": "active",
        "fields": {"name": first, "last_name": last, "company": form.company, "lead_source": "partner_inquiry", "partner_role": form.role},
    }
    if form.message:
        payload["fields"]["contact_message"] = form.message[:1000]
    headers = {"Authorization": f"Bearer {MAILERLITE_API_TOKEN}", "Content-Type": "application/json", "Accept": "application/json"}
    async with httpx.AsyncClient(timeout=10) as http:
        resp = await http.post(MAILERLITE_URL, json=payload, headers=headers)
    if resp.status_code not in (200, 201):
        logger.error(f"MailerLite partner error {resp.status_code}: {resp.text}")
        raise HTTPException(status_code=502, detail="Could not submit inquiry. Please try again.")
    return {"ok": True}


@router.post("/diagnostic")
async def submit_diagnostic(data: DiagnosticSubmit):
    payload = {
        "email": data.email, "status": "active",
        "fields": {"diagnostic_result": data.result, "diagnostic_score": f"{data.score}/28", "red_flags": str(data.red_count), "yellow_flags": str(data.yellow_count), "lead_source": "diagnostic_assessment"},
    }
    headers = {"Authorization": f"Bearer {MAILERLITE_API_TOKEN}", "Content-Type": "application/json", "Accept": "application/json"}
    async with httpx.AsyncClient(timeout=10) as http:
        resp = await http.post(MAILERLITE_URL, json=payload, headers=headers)
    if resp.status_code not in (200, 201):
        logger.error(f"MailerLite diagnostic error: {resp.text}")
        raise HTTPException(status_code=502, detail="Could not log result.")
    return {"ok": True, "result": data.result}


@router.post("/reach")
async def submit_reach(data: REACHSubmit):
    tag_map = {"GO": "REACH_GO", "WAIT": "REACH_WAIT", "NO-GO": "REACH_NOGO"}
    payload = {
        "email": data.email, "status": "active",
        "fields": {
            "lead_source": f"reach_{data.result.lower().replace('-', '_')}",
            "reach_result": data.result, "reach_total_score": str(data.total_score),
            "reach_resources": str(data.category_scores.r), "reach_experience": str(data.category_scores.e),
            "reach_authority": str(data.category_scores.a), "reach_commitment": str(data.category_scores.c),
            "reach_hustle": str(data.category_scores.h), "reach_open_response": data.open_response or "",
            "reach_tag": tag_map.get(data.result, "REACH_COMPLETE"),
        },
    }
    headers = {"Authorization": f"Bearer {MAILERLITE_API_TOKEN}", "Content-Type": "application/json", "Accept": "application/json"}
    async with httpx.AsyncClient(timeout=10) as http:
        resp = await http.post(MAILERLITE_URL, json=payload, headers=headers)
    if resp.status_code not in (200, 201):
        logger.error(f"MailerLite REACH error {resp.status_code}: {resp.text}")
        raise HTTPException(status_code=502, detail="Could not save assessment.")
    subject, html = _build_reach_email(data.result, data.total_score, data.category_scores, data.email)
    asyncio.create_task(send_mailersend_email(data.email, data.email.split("@")[0], subject, html))
    return {"ok": True, "result": data.result}


@router.post("/admission")
async def submit_admission(data: AdmissionSubmit):
    payload = {
        "email": data.email, "status": "active",
        "fields": {"name": data.name, "lead_source": "admission_request", "usdot_number": data.usdot_number, "cohort_preference": data.cohort_preference, "admission_message": data.message or "", "admission_requested": "true"},
    }
    headers = {"Authorization": f"Bearer {MAILERLITE_API_TOKEN}", "Content-Type": "application/json", "Accept": "application/json"}
    async with httpx.AsyncClient(timeout=10) as http:
        resp = await http.post(MAILERLITE_URL, json=payload, headers=headers)
    if resp.status_code not in (200, 201):
        logger.error(f"MailerLite admission error {resp.status_code}: {resp.text}")
        raise HTTPException(status_code=502, detail="Could not save submission.")
    return {"ok": True}


@router.post("/admission-request")
async def submit_admission_request(data: AdmissionRequestNew):
    now = datetime.now(timezone.utc)
    record = {
        "carrier_name": data.carrier_name, "email": data.email,
        "dot_mc_number": data.dot_mc_number or "", "authority_activation_date": data.authority_activation_date or "",
        "compliance_status": data.compliance_status, "lane": data.lane, "message": data.message or "",
        "source": "admission_form", "submission_date": now.isoformat(), "status": "pending_review",
    }
    await db.admission_requests.insert_one(record)
    admission_id = str(record["_id"])
    lane_label = "Box Truck" if data.lane == "box_truck" else "Semi / Tractor-Trailer"
    ml_payload = {
        "email": data.email, "status": "active",
        "fields": {"name": data.carrier_name, "lead_source": "admission_request", "admission_status": "pending_review", "admission_lane": lane_label, "admission_compliance_status": data.compliance_status},
    }
    headers = {"Authorization": f"Bearer {MAILERLITE_API_TOKEN}", "Content-Type": "application/json", "Accept": "application/json"}
    try:
        async with httpx.AsyncClient(timeout=10) as http:
            ml_resp = await http.post(MAILERLITE_URL, json=ml_payload, headers=headers)
        if ml_resp.status_code not in (200, 201):
            logger.error(f"MailerLite admission-request error {ml_resp.status_code}: {ml_resp.text}")
    except Exception as exc:
        logger.error(f"MailerLite admission-request failed: {exc}")
    act_date = data.authority_activation_date or "Not provided"
    notify_html = f"""
    <div style="font-family:'Inter',sans-serif;max-width:600px;margin:0 auto;background:#002244;color:#f4f7fb;padding:48px 40px;border-top:4px solid #C5A059;">
      <p style="font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:#C5A059;margin:0 0 24px;">LaunchPath Operating Standard &nbsp;|&nbsp; New Admission Request</p>
      <h1 style="font-family:'Manrope',sans-serif;font-size:26px;font-weight:700;color:#ffffff;margin:0 0 6px;">New Admission Request</h1>
      <p style="font-size:15px;color:rgba(255,255,255,0.65);margin:0 0 28px;">A qualified operator has submitted an admission request.</p>
      <div style="background:#0F1E35;border-left:3px solid #C5A059;padding:20px 24px;margin:0 0 28px;">
        <table style="width:100%;border-collapse:collapse;">
          <tr><td style="padding:6px 0;font-size:13px;color:rgba(255,255,255,0.55);width:180px;">Carrier Name</td><td style="padding:6px 0;font-size:13px;color:#ffffff;font-weight:600;">{data.carrier_name}</td></tr>
          <tr><td style="padding:6px 0;font-size:13px;color:rgba(255,255,255,0.55);">Email</td><td style="padding:6px 0;font-size:13px;color:#C5A059;">{data.email}</td></tr>
          <tr><td style="padding:6px 0;font-size:13px;color:rgba(255,255,255,0.55);">DOT / MC Number</td><td style="padding:6px 0;font-size:13px;color:#ffffff;">{data.dot_mc_number or "Not provided"}</td></tr>
          <tr><td style="padding:6px 0;font-size:13px;color:rgba(255,255,255,0.55);">Authority Active Since</td><td style="padding:6px 0;font-size:13px;color:#ffffff;">{act_date}</td></tr>
          <tr><td style="padding:6px 0;font-size:13px;color:rgba(255,255,255,0.55);">Compliance Status</td><td style="padding:6px 0;font-size:13px;color:#ffffff;">{data.compliance_status}</td></tr>
          <tr><td style="padding:6px 0;font-size:13px;color:rgba(255,255,255,0.55);">Lane / Equipment</td><td style="padding:6px 0;font-size:13px;color:#ffffff;">{lane_label}</td></tr>
        </table>
      </div>
      {f'<div style="background:#0a1a2e;border-left:3px solid rgba(197,160,89,0.4);padding:16px 20px;margin:0 0 28px;"><p style="font-size:11px;letter-spacing:0.14em;text-transform:uppercase;color:rgba(197,160,89,0.7);margin:0 0 8px;">Operator Note</p><p style="font-size:14px;color:rgba(255,255,255,0.75);line-height:1.65;margin:0;">{data.message}</p></div>' if data.message else ""}
      <p style="font-size:13px;color:rgba(255,255,255,0.45);margin:28px 0 0;line-height:1.6;">Submitted {now.strftime("%B %d, %Y at %H:%M UTC")}</p>
    </div>"""
    asyncio.create_task(send_mailersend_email(COACH_EMAIL, "Vince Lawrence", f"New Admission Request — {data.carrier_name}", notify_html, reply_to=data.email))
    return {"ok": True, "admission_id": admission_id}


@router.post("/ground0")
async def submit_ground0(data: Ground0Submit):
    payload = {"email": data.email, "status": "active", "fields": {"lead_source": "ground_0_complete", "ground_0_complete": "true"}}
    headers = {"Authorization": f"Bearer {MAILERLITE_API_TOKEN}", "Content-Type": "application/json", "Accept": "application/json"}
    try:
        async with httpx.AsyncClient(timeout=10) as http:
            resp = await http.post(MAILERLITE_URL, json=payload, headers=headers)
        if resp.status_code not in (200, 201):
            logger.error(f"MailerLite Ground 0 error {resp.status_code}: {resp.text}")
    except Exception as exc:
        logger.error(f"MailerLite Ground 0 request failed: {exc}")
    return {"ok": True}


@router.post("/sins-checklist")
async def sins_checklist_capture(data: SinsChecklistCapture):
    payload = {"email": data.email, "status": "active", "fields": {"lead_source": "sins_checklist_download", "lead_group": "16 Deadly Sins Downloads"}}
    headers = {"Authorization": f"Bearer {MAILERLITE_API_TOKEN}", "Content-Type": "application/json", "Accept": "application/json"}
    try:
        async with httpx.AsyncClient(timeout=10) as http:
            resp = await http.post(MAILERLITE_URL, json=payload, headers=headers)
        if resp.status_code not in (200, 201):
            logger.error(f"MailerLite sins checklist error {resp.status_code}: {resp.text}")
    except Exception as exc:
        logger.error(f"MailerLite sins checklist request failed: {exc}")
    return {"ok": True}


@router.post("/cpm/email-capture")
async def cpm_email_capture(data: CPMEmailCapture):
    payload = {"email": data.email, "status": "active", "fields": {"lead_source": "cpm_calculator"}}
    headers = {"Authorization": f"Bearer {MAILERLITE_API_TOKEN}", "Content-Type": "application/json", "Accept": "application/json"}
    try:
        async with httpx.AsyncClient(timeout=10) as http:
            resp = await http.post(MAILERLITE_URL, json=payload, headers=headers)
        if resp.status_code not in (200, 201):
            logger.error(f"MailerLite CPM error {resp.status_code}: {resp.text}")
    except Exception as exc:
        logger.error(f"MailerLite CPM request failed: {exc}")
    return {"ok": True}
